name: Remote Deploy
on:
  repository_dispatch:
    types: [deploy]
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      ipa_url: ${{ github.event.client_payload.ipa_url }}
      is_testflight: ${{ github.event.client_payload.is_testflight || false }}
      release: ${{ github.event.client_payload.release || true }}
    secrets: inherit
